networks:
  default: studionet
  studionet:
    accounts:
      - "${WEBWITNESS_TEST_STEWARD_KEY}"
      - "${WEBWITNESS_TEST_REQUESTER_KEY}"
  localnet: {}
paths:
  contracts: contracts
  artifacts: artifacts
environment: .env
